Update Workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,32 +25,18 @@ jobs:
           cd /home/api/api
           git pull origin dev
           
-          # Выполняем миграции
-          cd Miel
-          echo "Running migrations..."
-          python /app/manage.py migrate || {
-
-            # Если миграции не прошли, выполняем flush (с подтверждением)
-            echo "Migration failed, running flush..."
-            python /app/manage.py flush --no-input
-
-            # Повторяем миграции после flush
-            echo "Re-running migrations after flush..."
-            python /app/manage.py migrate
-
-            # Создание суперпользователя, если требуется
-            echo "Creating superuser..."
-            echo "from hr.models import CustomUser as User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python /app/manage.py shell
-
-          }
-
-          # Если миграции прошли успешно
-          echo "Migrations successful!"
-          cd ..
-
-          # Продолжаем запуск контейнеров
-          echo "Stopping old containers..."
+          # Останавливаем старые контейнеры
           sudo docker-compose down
-          echo "Rebuilding and starting containers..."
-          sudo docker-compose up -d --build
+            
+          # Собираем новые образы
+          sudo docker-compose build
+            
+          # Запускаем миграции
+          sudo docker-compose run --rm app python manage.py migrate || {
+            echo "Migrations failed!"
+            exit 1
+          }
+            
+          # Поднимаем контейнеры после успешной миграции
+          sudo docker-compose up -d
           EOF
